#!/usr/bin/env node
// Bundles the ES-module src/ into ONE classic-script IIFE that WebTAK's loadScript()
// can load (it injects a plain <script>, so import/export are illegal).
//
// The src/ modules have no top-level name collisions and only call getConfig()/etc.
// at runtime, so a dependency-ordered concatenation with import/export stripped is a
// valid single scope. Run:  node build.js
//
// Output: dist/webtak-video-viewer.plugin.js

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'plugin', 'src');
const OUT_DIR = path.join(__dirname, 'dist');
const OUT = path.join(OUT_DIR, 'webtak-video-viewer.plugin.js');

// Dependency order: config first (defines DEFAULTS/current), core near the end
// (constructs the singleton), index last (boot()).
const MODULES = [
  'config.js',
  'restreamer.js',
  'tak-video-library.js',
  'player.js',
  'styles.js',
  'window-manager.js',
  'ui.js',
  'core.js',
];

function stripModuleSyntax(code) {
  return code
    .split('\n')
    .filter((line) => !/^\s*import\s.+from\s.+;?\s*$/.test(line))     // drop `import … from …`
    .map((line) => line
      .replace(/^\s*export\s+default\s+.+;?\s*$/, '')                  // drop `export default …;`
      .replace(/^\s*export\s*\{[^}]*\};?\s*$/, '')                     // drop `export { … };`
      .replace(/^(\s*)export\s+/, '$1'))                               // `export const/function/class` → keep decl
    .join('\n');
}

let out = `/* WebTAK Video Viewer — bundled plugin (classic script). Generated by build.js. Do not edit here. */\n`;
out += `(function () {\n'use strict';\n`;

for (const m of MODULES) {
  const code = fs.readFileSync(path.join(SRC, m), 'utf8');
  out += `\n/* ===== src/${m} ===== */\n` + stripModuleSyntax(code) + '\n';
}

// core.js defines `instance`; the WebTAK entry logic (was plugin/index.js) refers to
// it as `viewer`. Alias, then inline the entry logic (import/export stripped).
out += `\n/* ===== WebTAK entry (from plugin/index.js) ===== */\n`;
out += `const viewer = instance;\n`;
const entry = stripModuleSyntax(fs.readFileSync(path.join(__dirname, 'plugin', 'index.js'), 'utf8'))
  .replace(/^\s*const\s+viewer\s*=.*$/m, '');   // guard: no duplicate alias if present
out += entry + '\n';

out += `})();\n`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, out);

// Sanity: no ESM syntax must survive into a classic script.
const leaked = out.split('\n').filter((l) => /^\s*(import|export)\s/.test(l));
if (leaked.length) {
  console.error('ERROR: ESM syntax leaked into bundle:\n' + leaked.join('\n'));
  process.exit(1);
}
console.log(`Built ${path.relative(__dirname, OUT)} (${(out.length / 1024).toFixed(1)} KB)`);
